### ISSUE TITLE
Failed to launch application

### ISSUE THREAD

**Issue by seandomal** [Quantico-Bullet/PyBeam-QA#5]
I downloaded your code to my local computer and tried running through the command prompt and got this error:

C:\Users\S214061\OneDrive - University of Texas Southwestern\Desktop\PyBeam-QA-main\PyBeam-QA-main>python main.py # or python3 main.py
Traceback (most recent call last):
  File "C:\Users\S214061\OneDrive - University of Texas Southwestern\Desktop\PyBeam-QA-main\PyBeam-QA-main\main.py", line 6, in <module>
    from ui.appMainWin import AppMainWin
  File "C:\Users\S214061\OneDrive - University of Texas Southwestern\Desktop\PyBeam-QA-main\PyBeam-QA-main\ui\appMainWin.py", line 7, in <module>
    from ui.qaToolsWindow import QAToolsWindow
  File "C:\Users\S214061\OneDrive - University of Texas Southwestern\Desktop\PyBeam-QA-main\PyBeam-QA-main\ui\qaToolsWindow.py", line 5, in <module>
    from ui.utilsWidgets.statusbar_widgets import AnalysisInfoLabel
  File "C:\Users\S214061\OneDrive - University of Texas Southwestern\Desktop\PyBeam-QA-main\PyBeam-QA-main\ui\utilsWidgets\statusbar_widgets.py", line 6, in <module>
    class AnalysisInfoLabel(QWidget):
  File "C:\Users\S214061\OneDrive - University of Texas Southwestern\Desktop\PyBeam-QA-main\PyBeam-QA-main\ui\utilsWidgets\statusbar_widgets.py", line 28, in AnalysisInfoLabel
    def set_message(self, state: int = IDLE, message: str | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Can you help me reconcile this error and get it working?

**Comment by Quantico-Bullet** [comment]
Hi there. Please note that the minimum python version required is 3.10+. What version of python are you running? 

A similar issue was report in one of the closed issues.
